name: 'Build Docs'

on:
  push:
    branches:
      - 'main'
      - 'master'
  schedule:
    # rebuild docs at 10 AM every Monday
    - cron:  '0 10 * * 1'

jobs:
  build_docs:
    runs-on: ubuntu-latest
    env:
      PIPENV_PIPFILE: docs/scripts/Pipfile
    steps:
      - uses: actions/checkout@v1
      - name: Install Roswell
        env:
          LISP: sbcl-bin
        run: |
          curl -L https://raw.githubusercontent.com/roswell/roswell/master/scripts/install-for-ci.sh | sh
          echo /home/runner/.roswell/bin >> $GITHUB_PATH
      - name: Install Ultralisp
        run: ros -e '(ql-dist:install-dist "http://dist.ultralisp.org/" :prompt nil)'
      - name: Install Pythonn 3.7
        run: |
          sudo apt-get update
          sudo apt-get install --yes software-properties-common
          sudo add-apt-repository --yes ppa:deadsnakes/ppa
          sudo apt-get install python3.7
      - name: Check Python Version
        run: |
          python3.7 --version
      - name: Check CL Version
        run: |
          ros install 40ants/cl-info
          cl-info
      - name: Install cldomain Helper
        run: ros install 40ants/cldomain
      - name: Install Pipenv
        run: |
          pip3 install pipenv
          echo /home/runner/.local/bin >> $GITHUB_PATH
      - name: Install Python Dependencies
        run: /home/runner/.local/bin/pipenv install
      - name: Build docs
        run: /home/runner/.local/bin/pipenv run docs/scripts/build.ros
